development:
    dialect: postgres
    datasource: dbname=goauction_db sslmode=disable
    dir: migrations/postgres
    table: migrations

test:
    dialect: postgres
    datasource: dbname=goauction_db_test sslmode=disable
    dir: migrations/postgres
    table: migrations