// Code generated by go-queryset. DO NOT EDIT.
package models

import (
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/jinzhu/gorm"
)

// ===== BEGIN of all query sets

// ===== BEGIN of query set AccessTokenQuerySet

// AccessTokenQuerySet is an queryset type for AccessToken
type AccessTokenQuerySet struct {
	db *gorm.DB
}

// NewAccessTokenQuerySet constructs new AccessTokenQuerySet
func NewAccessTokenQuerySet(db *gorm.DB) AccessTokenQuerySet {
	return AccessTokenQuerySet{
		db: db.Model(&AccessToken{}),
	}
}

func (qs AccessTokenQuerySet) w(db *gorm.DB) AccessTokenQuerySet {
	return NewAccessTokenQuerySet(db)
}

func (qs AccessTokenQuerySet) Select(fields ...AccessTokenDBSchemaField) AccessTokenQuerySet {
	names := []string{}
	for _, f := range fields {
		names = append(names, f.String())
	}

	return qs.w(qs.db.Select(strings.Join(names, ",")))
}

// Create is an autogenerated method
// nolint: dupl
func (o *AccessToken) Create(db *gorm.DB) error {
	return db.Create(o).Error
}

// Delete is an autogenerated method
// nolint: dupl
func (o *AccessToken) Delete(db *gorm.DB) error {
	return db.Delete(o).Error
}

// All is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) All(ret *[]AccessToken) error {
	return qs.db.Find(ret).Error
}

// Count is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) Count() (int, error) {
	var count int
	err := qs.db.Count(&count).Error
	return count, err
}

// CreatedEq is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) CreatedEq(created time.Time) AccessTokenQuerySet {
	return qs.w(qs.db.Where("created = ?", created))
}

// CreatedGt is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) CreatedGt(created time.Time) AccessTokenQuerySet {
	return qs.w(qs.db.Where("created > ?", created))
}

// CreatedGte is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) CreatedGte(created time.Time) AccessTokenQuerySet {
	return qs.w(qs.db.Where("created >= ?", created))
}

// CreatedLt is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) CreatedLt(created time.Time) AccessTokenQuerySet {
	return qs.w(qs.db.Where("created < ?", created))
}

// CreatedLte is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) CreatedLte(created time.Time) AccessTokenQuerySet {
	return qs.w(qs.db.Where("created <= ?", created))
}

// CreatedNe is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) CreatedNe(created time.Time) AccessTokenQuerySet {
	return qs.w(qs.db.Where("created != ?", created))
}

// Delete is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) Delete() error {
	return qs.db.Delete(AccessToken{}).Error
}

// DeleteNum is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) DeleteNum() (int64, error) {
	db := qs.db.Delete(AccessToken{})
	return db.RowsAffected, db.Error
}

// DeleteNumUnscoped is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) DeleteNumUnscoped() (int64, error) {
	db := qs.db.Unscoped().Delete(AccessToken{})
	return db.RowsAffected, db.Error
}

// GetDB is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) GetDB() *gorm.DB {
	return qs.db
}

// GetUpdater is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) GetUpdater() AccessTokenUpdater {
	return NewAccessTokenUpdater(qs.db)
}

// Limit is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) Limit(limit int) AccessTokenQuerySet {
	return qs.w(qs.db.Limit(limit))
}

// Offset is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) Offset(offset int) AccessTokenQuerySet {
	return qs.w(qs.db.Offset(offset))
}

// One is used to retrieve one result. It returns gorm.ErrRecordNotFound
// if nothing was fetched
func (qs AccessTokenQuerySet) One(ret *AccessToken) error {
	return qs.db.First(ret).Error
}

// OrderAscByCreated is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) OrderAscByCreated() AccessTokenQuerySet {
	return qs.w(qs.db.Order("created ASC"))
}

// OrderAscByToken is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) OrderAscByToken() AccessTokenQuerySet {
	return qs.w(qs.db.Order("token ASC"))
}

// OrderAscByUserID is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) OrderAscByUserID() AccessTokenQuerySet {
	return qs.w(qs.db.Order("user_id ASC"))
}

// OrderAscByValidThru is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) OrderAscByValidThru() AccessTokenQuerySet {
	return qs.w(qs.db.Order("valid_thru ASC"))
}

// OrderDescByCreated is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) OrderDescByCreated() AccessTokenQuerySet {
	return qs.w(qs.db.Order("created DESC"))
}

// OrderDescByToken is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) OrderDescByToken() AccessTokenQuerySet {
	return qs.w(qs.db.Order("token DESC"))
}

// OrderDescByUserID is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) OrderDescByUserID() AccessTokenQuerySet {
	return qs.w(qs.db.Order("user_id DESC"))
}

// OrderDescByValidThru is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) OrderDescByValidThru() AccessTokenQuerySet {
	return qs.w(qs.db.Order("valid_thru DESC"))
}

// PreloadUser is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) PreloadUser() AccessTokenQuerySet {
	return qs.w(qs.db.Preload("User"))
}

// TokenEq is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) TokenEq(token string) AccessTokenQuerySet {
	return qs.w(qs.db.Where("token = ?", token))
}

// TokenGt is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) TokenGt(token string) AccessTokenQuerySet {
	return qs.w(qs.db.Where("token > ?", token))
}

// TokenGte is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) TokenGte(token string) AccessTokenQuerySet {
	return qs.w(qs.db.Where("token >= ?", token))
}

// TokenIn is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) TokenIn(token ...string) AccessTokenQuerySet {
	if len(token) == 0 {
		qs.db.AddError(errors.New("must at least pass one token in TokenIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("token IN (?)", token))
}

// TokenLike is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) TokenLike(token string) AccessTokenQuerySet {
	return qs.w(qs.db.Where("token LIKE ?", token))
}

// TokenLt is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) TokenLt(token string) AccessTokenQuerySet {
	return qs.w(qs.db.Where("token < ?", token))
}

// TokenLte is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) TokenLte(token string) AccessTokenQuerySet {
	return qs.w(qs.db.Where("token <= ?", token))
}

// TokenNe is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) TokenNe(token string) AccessTokenQuerySet {
	return qs.w(qs.db.Where("token != ?", token))
}

// TokenNotIn is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) TokenNotIn(token ...string) AccessTokenQuerySet {
	if len(token) == 0 {
		qs.db.AddError(errors.New("must at least pass one token in TokenNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("token NOT IN (?)", token))
}

// TokenNotlike is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) TokenNotlike(token string) AccessTokenQuerySet {
	return qs.w(qs.db.Where("token NOT LIKE ?", token))
}

// UserIDEq is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) UserIDEq(userID int64) AccessTokenQuerySet {
	return qs.w(qs.db.Where("user_id = ?", userID))
}

// UserIDGt is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) UserIDGt(userID int64) AccessTokenQuerySet {
	return qs.w(qs.db.Where("user_id > ?", userID))
}

// UserIDGte is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) UserIDGte(userID int64) AccessTokenQuerySet {
	return qs.w(qs.db.Where("user_id >= ?", userID))
}

// UserIDIn is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) UserIDIn(userID ...int64) AccessTokenQuerySet {
	if len(userID) == 0 {
		qs.db.AddError(errors.New("must at least pass one userID in UserIDIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("user_id IN (?)", userID))
}

// UserIDLt is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) UserIDLt(userID int64) AccessTokenQuerySet {
	return qs.w(qs.db.Where("user_id < ?", userID))
}

// UserIDLte is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) UserIDLte(userID int64) AccessTokenQuerySet {
	return qs.w(qs.db.Where("user_id <= ?", userID))
}

// UserIDNe is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) UserIDNe(userID int64) AccessTokenQuerySet {
	return qs.w(qs.db.Where("user_id != ?", userID))
}

// UserIDNotIn is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) UserIDNotIn(userID ...int64) AccessTokenQuerySet {
	if len(userID) == 0 {
		qs.db.AddError(errors.New("must at least pass one userID in UserIDNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("user_id NOT IN (?)", userID))
}

// ValidThruEq is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) ValidThruEq(validThru time.Time) AccessTokenQuerySet {
	return qs.w(qs.db.Where("valid_thru = ?", validThru))
}

// ValidThruGt is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) ValidThruGt(validThru time.Time) AccessTokenQuerySet {
	return qs.w(qs.db.Where("valid_thru > ?", validThru))
}

// ValidThruGte is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) ValidThruGte(validThru time.Time) AccessTokenQuerySet {
	return qs.w(qs.db.Where("valid_thru >= ?", validThru))
}

// ValidThruLt is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) ValidThruLt(validThru time.Time) AccessTokenQuerySet {
	return qs.w(qs.db.Where("valid_thru < ?", validThru))
}

// ValidThruLte is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) ValidThruLte(validThru time.Time) AccessTokenQuerySet {
	return qs.w(qs.db.Where("valid_thru <= ?", validThru))
}

// ValidThruNe is an autogenerated method
// nolint: dupl
func (qs AccessTokenQuerySet) ValidThruNe(validThru time.Time) AccessTokenQuerySet {
	return qs.w(qs.db.Where("valid_thru != ?", validThru))
}

// SetCreated is an autogenerated method
// nolint: dupl
func (u AccessTokenUpdater) SetCreated(created time.Time) AccessTokenUpdater {
	u.fields[string(AccessTokenDBSchema.Created)] = created
	return u
}

// SetToken is an autogenerated method
// nolint: dupl
func (u AccessTokenUpdater) SetToken(token string) AccessTokenUpdater {
	u.fields[string(AccessTokenDBSchema.Token)] = token
	return u
}

// SetUser is an autogenerated method
// nolint: dupl
func (u AccessTokenUpdater) SetUser(user User) AccessTokenUpdater {
	u.fields[string(AccessTokenDBSchema.User)] = user
	return u
}

// SetUserID is an autogenerated method
// nolint: dupl
func (u AccessTokenUpdater) SetUserID(userID int64) AccessTokenUpdater {
	u.fields[string(AccessTokenDBSchema.UserID)] = userID
	return u
}

// SetValidThru is an autogenerated method
// nolint: dupl
func (u AccessTokenUpdater) SetValidThru(validThru time.Time) AccessTokenUpdater {
	u.fields[string(AccessTokenDBSchema.ValidThru)] = validThru
	return u
}

// Update is an autogenerated method
// nolint: dupl
func (u AccessTokenUpdater) Update() error {
	return u.db.Updates(u.fields).Error
}

// UpdateNum is an autogenerated method
// nolint: dupl
func (u AccessTokenUpdater) UpdateNum() (int64, error) {
	db := u.db.Updates(u.fields)
	return db.RowsAffected, db.Error
}

// ===== END of query set AccessTokenQuerySet

// ===== BEGIN of AccessToken modifiers

// AccessTokenDBSchemaField describes database schema field. It requires for method 'Update'
type AccessTokenDBSchemaField string

// String method returns string representation of field.
// nolint: dupl
func (f AccessTokenDBSchemaField) String() string {
	return string(f)
}

// AccessTokenDBSchema stores db field names of AccessToken
var AccessTokenDBSchema = struct {
	UserID    AccessTokenDBSchemaField
	User      AccessTokenDBSchemaField
	Token     AccessTokenDBSchemaField
	Created   AccessTokenDBSchemaField
	ValidThru AccessTokenDBSchemaField
}{

	UserID:    AccessTokenDBSchemaField("user_id"),
	User:      AccessTokenDBSchemaField("user"),
	Token:     AccessTokenDBSchemaField("token"),
	Created:   AccessTokenDBSchemaField("created"),
	ValidThru: AccessTokenDBSchemaField("valid_thru"),
}

// Update updates AccessToken fields by primary key
// nolint: dupl
func (o *AccessToken) Update(db *gorm.DB, fields ...AccessTokenDBSchemaField) error {
	dbNameToFieldName := map[string]interface{}{
		"user_id":    o.UserID,
		"user":       o.User,
		"token":      o.Token,
		"created":    o.Created,
		"valid_thru": o.ValidThru,
	}
	u := map[string]interface{}{}
	for _, f := range fields {
		fs := f.String()
		u[fs] = dbNameToFieldName[fs]
	}
	if err := db.Model(o).Updates(u).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return err
		}

		return fmt.Errorf("can't update AccessToken %v fields %v: %s",
			o, fields, err)
	}

	return nil
}

// AccessTokenUpdater is an AccessToken updates manager
type AccessTokenUpdater struct {
	fields map[string]interface{}
	db     *gorm.DB
}

// NewAccessTokenUpdater creates new AccessToken updater
// nolint: dupl
func NewAccessTokenUpdater(db *gorm.DB) AccessTokenUpdater {
	return AccessTokenUpdater{
		fields: map[string]interface{}{},
		db:     db.Model(&AccessToken{}),
	}
}

// ===== END of AccessToken modifiers

// ===== BEGIN of query set RegisterUserQuerySet

// RegisterUserQuerySet is an queryset type for RegisterUser
type RegisterUserQuerySet struct {
	db *gorm.DB
}

// NewRegisterUserQuerySet constructs new RegisterUserQuerySet
func NewRegisterUserQuerySet(db *gorm.DB) RegisterUserQuerySet {
	return RegisterUserQuerySet{
		db: db.Model(&RegisterUser{}),
	}
}

func (qs RegisterUserQuerySet) w(db *gorm.DB) RegisterUserQuerySet {
	return NewRegisterUserQuerySet(db)
}

func (qs RegisterUserQuerySet) Select(fields ...RegisterUserDBSchemaField) RegisterUserQuerySet {
	names := []string{}
	for _, f := range fields {
		names = append(names, f.String())
	}

	return qs.w(qs.db.Select(strings.Join(names, ",")))
}

// Create is an autogenerated method
// nolint: dupl
func (o *RegisterUser) Create(db *gorm.DB) error {
	return db.Create(o).Error
}

// Delete is an autogenerated method
// nolint: dupl
func (o *RegisterUser) Delete(db *gorm.DB) error {
	return db.Delete(o).Error
}

// All is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) All(ret *[]RegisterUser) error {
	return qs.db.Find(ret).Error
}

// CodeEq is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) CodeEq(code string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("code = ?", code))
}

// CodeGt is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) CodeGt(code string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("code > ?", code))
}

// CodeGte is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) CodeGte(code string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("code >= ?", code))
}

// CodeIn is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) CodeIn(code ...string) RegisterUserQuerySet {
	if len(code) == 0 {
		qs.db.AddError(errors.New("must at least pass one code in CodeIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("code IN (?)", code))
}

// CodeLike is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) CodeLike(code string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("code LIKE ?", code))
}

// CodeLt is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) CodeLt(code string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("code < ?", code))
}

// CodeLte is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) CodeLte(code string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("code <= ?", code))
}

// CodeNe is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) CodeNe(code string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("code != ?", code))
}

// CodeNotIn is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) CodeNotIn(code ...string) RegisterUserQuerySet {
	if len(code) == 0 {
		qs.db.AddError(errors.New("must at least pass one code in CodeNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("code NOT IN (?)", code))
}

// CodeNotlike is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) CodeNotlike(code string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("code NOT LIKE ?", code))
}

// Count is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) Count() (int, error) {
	var count int
	err := qs.db.Count(&count).Error
	return count, err
}

// Delete is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) Delete() error {
	return qs.db.Delete(RegisterUser{}).Error
}

// DeleteNum is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) DeleteNum() (int64, error) {
	db := qs.db.Delete(RegisterUser{})
	return db.RowsAffected, db.Error
}

// DeleteNumUnscoped is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) DeleteNumUnscoped() (int64, error) {
	db := qs.db.Unscoped().Delete(RegisterUser{})
	return db.RowsAffected, db.Error
}

// EmailEq is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) EmailEq(email string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("email = ?", email))
}

// EmailGt is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) EmailGt(email string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("email > ?", email))
}

// EmailGte is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) EmailGte(email string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("email >= ?", email))
}

// EmailIn is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) EmailIn(email ...string) RegisterUserQuerySet {
	if len(email) == 0 {
		qs.db.AddError(errors.New("must at least pass one email in EmailIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("email IN (?)", email))
}

// EmailLike is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) EmailLike(email string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("email LIKE ?", email))
}

// EmailLt is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) EmailLt(email string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("email < ?", email))
}

// EmailLte is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) EmailLte(email string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("email <= ?", email))
}

// EmailNe is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) EmailNe(email string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("email != ?", email))
}

// EmailNotIn is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) EmailNotIn(email ...string) RegisterUserQuerySet {
	if len(email) == 0 {
		qs.db.AddError(errors.New("must at least pass one email in EmailNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("email NOT IN (?)", email))
}

// EmailNotlike is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) EmailNotlike(email string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("email NOT LIKE ?", email))
}

// FullNameEq is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) FullNameEq(fullName string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("full_name = ?", fullName))
}

// FullNameGt is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) FullNameGt(fullName string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("full_name > ?", fullName))
}

// FullNameGte is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) FullNameGte(fullName string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("full_name >= ?", fullName))
}

// FullNameIn is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) FullNameIn(fullName ...string) RegisterUserQuerySet {
	if len(fullName) == 0 {
		qs.db.AddError(errors.New("must at least pass one fullName in FullNameIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("full_name IN (?)", fullName))
}

// FullNameLike is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) FullNameLike(fullName string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("full_name LIKE ?", fullName))
}

// FullNameLt is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) FullNameLt(fullName string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("full_name < ?", fullName))
}

// FullNameLte is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) FullNameLte(fullName string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("full_name <= ?", fullName))
}

// FullNameNe is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) FullNameNe(fullName string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("full_name != ?", fullName))
}

// FullNameNotIn is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) FullNameNotIn(fullName ...string) RegisterUserQuerySet {
	if len(fullName) == 0 {
		qs.db.AddError(errors.New("must at least pass one fullName in FullNameNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("full_name NOT IN (?)", fullName))
}

// FullNameNotlike is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) FullNameNotlike(fullName string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("full_name NOT LIKE ?", fullName))
}

// GetDB is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) GetDB() *gorm.DB {
	return qs.db
}

// GetUpdater is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) GetUpdater() RegisterUserUpdater {
	return NewRegisterUserUpdater(qs.db)
}

// Limit is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) Limit(limit int) RegisterUserQuerySet {
	return qs.w(qs.db.Limit(limit))
}

// Offset is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) Offset(offset int) RegisterUserQuerySet {
	return qs.w(qs.db.Offset(offset))
}

// One is used to retrieve one result. It returns gorm.ErrRecordNotFound
// if nothing was fetched
func (qs RegisterUserQuerySet) One(ret *RegisterUser) error {
	return qs.db.First(ret).Error
}

// OrderAscByCode is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) OrderAscByCode() RegisterUserQuerySet {
	return qs.w(qs.db.Order("code ASC"))
}

// OrderAscByEmail is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) OrderAscByEmail() RegisterUserQuerySet {
	return qs.w(qs.db.Order("email ASC"))
}

// OrderAscByFullName is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) OrderAscByFullName() RegisterUserQuerySet {
	return qs.w(qs.db.Order("full_name ASC"))
}

// OrderAscByPhoneNum is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) OrderAscByPhoneNum() RegisterUserQuerySet {
	return qs.w(qs.db.Order("phone_num ASC"))
}

// OrderAscByRegisteredAt is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) OrderAscByRegisteredAt() RegisterUserQuerySet {
	return qs.w(qs.db.Order("registered_at ASC"))
}

// OrderAscByToken is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) OrderAscByToken() RegisterUserQuerySet {
	return qs.w(qs.db.Order("token ASC"))
}

// OrderDescByCode is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) OrderDescByCode() RegisterUserQuerySet {
	return qs.w(qs.db.Order("code DESC"))
}

// OrderDescByEmail is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) OrderDescByEmail() RegisterUserQuerySet {
	return qs.w(qs.db.Order("email DESC"))
}

// OrderDescByFullName is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) OrderDescByFullName() RegisterUserQuerySet {
	return qs.w(qs.db.Order("full_name DESC"))
}

// OrderDescByPhoneNum is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) OrderDescByPhoneNum() RegisterUserQuerySet {
	return qs.w(qs.db.Order("phone_num DESC"))
}

// OrderDescByRegisteredAt is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) OrderDescByRegisteredAt() RegisterUserQuerySet {
	return qs.w(qs.db.Order("registered_at DESC"))
}

// OrderDescByToken is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) OrderDescByToken() RegisterUserQuerySet {
	return qs.w(qs.db.Order("token DESC"))
}

// PhoneNumEq is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) PhoneNumEq(phoneNum string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("phone_num = ?", phoneNum))
}

// PhoneNumGt is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) PhoneNumGt(phoneNum string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("phone_num > ?", phoneNum))
}

// PhoneNumGte is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) PhoneNumGte(phoneNum string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("phone_num >= ?", phoneNum))
}

// PhoneNumIn is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) PhoneNumIn(phoneNum ...string) RegisterUserQuerySet {
	if len(phoneNum) == 0 {
		qs.db.AddError(errors.New("must at least pass one phoneNum in PhoneNumIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("phone_num IN (?)", phoneNum))
}

// PhoneNumLike is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) PhoneNumLike(phoneNum string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("phone_num LIKE ?", phoneNum))
}

// PhoneNumLt is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) PhoneNumLt(phoneNum string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("phone_num < ?", phoneNum))
}

// PhoneNumLte is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) PhoneNumLte(phoneNum string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("phone_num <= ?", phoneNum))
}

// PhoneNumNe is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) PhoneNumNe(phoneNum string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("phone_num != ?", phoneNum))
}

// PhoneNumNotIn is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) PhoneNumNotIn(phoneNum ...string) RegisterUserQuerySet {
	if len(phoneNum) == 0 {
		qs.db.AddError(errors.New("must at least pass one phoneNum in PhoneNumNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("phone_num NOT IN (?)", phoneNum))
}

// PhoneNumNotlike is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) PhoneNumNotlike(phoneNum string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("phone_num NOT LIKE ?", phoneNum))
}

// RegisteredAtEq is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) RegisteredAtEq(registeredAt time.Time) RegisterUserQuerySet {
	return qs.w(qs.db.Where("registered_at = ?", registeredAt))
}

// RegisteredAtGt is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) RegisteredAtGt(registeredAt time.Time) RegisterUserQuerySet {
	return qs.w(qs.db.Where("registered_at > ?", registeredAt))
}

// RegisteredAtGte is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) RegisteredAtGte(registeredAt time.Time) RegisterUserQuerySet {
	return qs.w(qs.db.Where("registered_at >= ?", registeredAt))
}

// RegisteredAtLt is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) RegisteredAtLt(registeredAt time.Time) RegisterUserQuerySet {
	return qs.w(qs.db.Where("registered_at < ?", registeredAt))
}

// RegisteredAtLte is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) RegisteredAtLte(registeredAt time.Time) RegisterUserQuerySet {
	return qs.w(qs.db.Where("registered_at <= ?", registeredAt))
}

// RegisteredAtNe is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) RegisteredAtNe(registeredAt time.Time) RegisterUserQuerySet {
	return qs.w(qs.db.Where("registered_at != ?", registeredAt))
}

// TokenEq is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) TokenEq(token string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("token = ?", token))
}

// TokenGt is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) TokenGt(token string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("token > ?", token))
}

// TokenGte is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) TokenGte(token string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("token >= ?", token))
}

// TokenIn is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) TokenIn(token ...string) RegisterUserQuerySet {
	if len(token) == 0 {
		qs.db.AddError(errors.New("must at least pass one token in TokenIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("token IN (?)", token))
}

// TokenLike is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) TokenLike(token string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("token LIKE ?", token))
}

// TokenLt is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) TokenLt(token string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("token < ?", token))
}

// TokenLte is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) TokenLte(token string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("token <= ?", token))
}

// TokenNe is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) TokenNe(token string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("token != ?", token))
}

// TokenNotIn is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) TokenNotIn(token ...string) RegisterUserQuerySet {
	if len(token) == 0 {
		qs.db.AddError(errors.New("must at least pass one token in TokenNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("token NOT IN (?)", token))
}

// TokenNotlike is an autogenerated method
// nolint: dupl
func (qs RegisterUserQuerySet) TokenNotlike(token string) RegisterUserQuerySet {
	return qs.w(qs.db.Where("token NOT LIKE ?", token))
}

// SetCode is an autogenerated method
// nolint: dupl
func (u RegisterUserUpdater) SetCode(code string) RegisterUserUpdater {
	u.fields[string(RegisterUserDBSchema.Code)] = code
	return u
}

// SetEmail is an autogenerated method
// nolint: dupl
func (u RegisterUserUpdater) SetEmail(email string) RegisterUserUpdater {
	u.fields[string(RegisterUserDBSchema.Email)] = email
	return u
}

// SetFullName is an autogenerated method
// nolint: dupl
func (u RegisterUserUpdater) SetFullName(fullName string) RegisterUserUpdater {
	u.fields[string(RegisterUserDBSchema.FullName)] = fullName
	return u
}

// SetPhoneNum is an autogenerated method
// nolint: dupl
func (u RegisterUserUpdater) SetPhoneNum(phoneNum string) RegisterUserUpdater {
	u.fields[string(RegisterUserDBSchema.PhoneNum)] = phoneNum
	return u
}

// SetRegisteredAt is an autogenerated method
// nolint: dupl
func (u RegisterUserUpdater) SetRegisteredAt(registeredAt time.Time) RegisterUserUpdater {
	u.fields[string(RegisterUserDBSchema.RegisteredAt)] = registeredAt
	return u
}

// SetToken is an autogenerated method
// nolint: dupl
func (u RegisterUserUpdater) SetToken(token string) RegisterUserUpdater {
	u.fields[string(RegisterUserDBSchema.Token)] = token
	return u
}

// Update is an autogenerated method
// nolint: dupl
func (u RegisterUserUpdater) Update() error {
	return u.db.Updates(u.fields).Error
}

// UpdateNum is an autogenerated method
// nolint: dupl
func (u RegisterUserUpdater) UpdateNum() (int64, error) {
	db := u.db.Updates(u.fields)
	return db.RowsAffected, db.Error
}

// ===== END of query set RegisterUserQuerySet

// ===== BEGIN of RegisterUser modifiers

// RegisterUserDBSchemaField describes database schema field. It requires for method 'Update'
type RegisterUserDBSchemaField string

// String method returns string representation of field.
// nolint: dupl
func (f RegisterUserDBSchemaField) String() string {
	return string(f)
}

// RegisterUserDBSchema stores db field names of RegisterUser
var RegisterUserDBSchema = struct {
	FullName     RegisterUserDBSchemaField
	Email        RegisterUserDBSchemaField
	PhoneNum     RegisterUserDBSchemaField
	Token        RegisterUserDBSchemaField
	Code         RegisterUserDBSchemaField
	RegisteredAt RegisterUserDBSchemaField
}{

	FullName:     RegisterUserDBSchemaField("full_name"),
	Email:        RegisterUserDBSchemaField("email"),
	PhoneNum:     RegisterUserDBSchemaField("phone_num"),
	Token:        RegisterUserDBSchemaField("token"),
	Code:         RegisterUserDBSchemaField("code"),
	RegisteredAt: RegisterUserDBSchemaField("registered_at"),
}

// Update updates RegisterUser fields by primary key
// nolint: dupl
func (o *RegisterUser) Update(db *gorm.DB, fields ...RegisterUserDBSchemaField) error {
	dbNameToFieldName := map[string]interface{}{
		"full_name":     o.FullName,
		"email":         o.Email,
		"phone_num":     o.PhoneNum,
		"token":         o.Token,
		"code":          o.Code,
		"registered_at": o.RegisteredAt,
	}
	u := map[string]interface{}{}
	for _, f := range fields {
		fs := f.String()
		u[fs] = dbNameToFieldName[fs]
	}
	if err := db.Model(o).Updates(u).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return err
		}

		return fmt.Errorf("can't update RegisterUser %v fields %v: %s",
			o, fields, err)
	}

	return nil
}

// RegisterUserUpdater is an RegisterUser updates manager
type RegisterUserUpdater struct {
	fields map[string]interface{}
	db     *gorm.DB
}

// NewRegisterUserUpdater creates new RegisterUser updater
// nolint: dupl
func NewRegisterUserUpdater(db *gorm.DB) RegisterUserUpdater {
	return RegisterUserUpdater{
		fields: map[string]interface{}{},
		db:     db.Model(&RegisterUser{}),
	}
}

// ===== END of RegisterUser modifiers

// ===== BEGIN of query set UserPasshashQuerySet

// UserPasshashQuerySet is an queryset type for UserPasshash
type UserPasshashQuerySet struct {
	db *gorm.DB
}

// NewUserPasshashQuerySet constructs new UserPasshashQuerySet
func NewUserPasshashQuerySet(db *gorm.DB) UserPasshashQuerySet {
	return UserPasshashQuerySet{
		db: db.Model(&UserPasshash{}),
	}
}

func (qs UserPasshashQuerySet) w(db *gorm.DB) UserPasshashQuerySet {
	return NewUserPasshashQuerySet(db)
}

func (qs UserPasshashQuerySet) Select(fields ...UserPasshashDBSchemaField) UserPasshashQuerySet {
	names := []string{}
	for _, f := range fields {
		names = append(names, f.String())
	}

	return qs.w(qs.db.Select(strings.Join(names, ",")))
}

// Create is an autogenerated method
// nolint: dupl
func (o *UserPasshash) Create(db *gorm.DB) error {
	return db.Create(o).Error
}

// Delete is an autogenerated method
// nolint: dupl
func (o *UserPasshash) Delete(db *gorm.DB) error {
	return db.Delete(o).Error
}

// All is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) All(ret *[]UserPasshash) error {
	return qs.db.Find(ret).Error
}

// Count is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) Count() (int, error) {
	var count int
	err := qs.db.Count(&count).Error
	return count, err
}

// CreatedEq is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) CreatedEq(created time.Time) UserPasshashQuerySet {
	return qs.w(qs.db.Where("created = ?", created))
}

// CreatedGt is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) CreatedGt(created time.Time) UserPasshashQuerySet {
	return qs.w(qs.db.Where("created > ?", created))
}

// CreatedGte is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) CreatedGte(created time.Time) UserPasshashQuerySet {
	return qs.w(qs.db.Where("created >= ?", created))
}

// CreatedLt is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) CreatedLt(created time.Time) UserPasshashQuerySet {
	return qs.w(qs.db.Where("created < ?", created))
}

// CreatedLte is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) CreatedLte(created time.Time) UserPasshashQuerySet {
	return qs.w(qs.db.Where("created <= ?", created))
}

// CreatedNe is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) CreatedNe(created time.Time) UserPasshashQuerySet {
	return qs.w(qs.db.Where("created != ?", created))
}

// Delete is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) Delete() error {
	return qs.db.Delete(UserPasshash{}).Error
}

// DeleteNum is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) DeleteNum() (int64, error) {
	db := qs.db.Delete(UserPasshash{})
	return db.RowsAffected, db.Error
}

// DeleteNumUnscoped is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) DeleteNumUnscoped() (int64, error) {
	db := qs.db.Unscoped().Delete(UserPasshash{})
	return db.RowsAffected, db.Error
}

// DeprecatedEq is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) DeprecatedEq(deprecated bool) UserPasshashQuerySet {
	return qs.w(qs.db.Where("deprecated = ?", deprecated))
}

// DeprecatedIn is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) DeprecatedIn(deprecated ...bool) UserPasshashQuerySet {
	if len(deprecated) == 0 {
		qs.db.AddError(errors.New("must at least pass one deprecated in DeprecatedIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("deprecated IN (?)", deprecated))
}

// DeprecatedNe is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) DeprecatedNe(deprecated bool) UserPasshashQuerySet {
	return qs.w(qs.db.Where("deprecated != ?", deprecated))
}

// DeprecatedNotIn is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) DeprecatedNotIn(deprecated ...bool) UserPasshashQuerySet {
	if len(deprecated) == 0 {
		qs.db.AddError(errors.New("must at least pass one deprecated in DeprecatedNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("deprecated NOT IN (?)", deprecated))
}

// GetDB is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) GetDB() *gorm.DB {
	return qs.db
}

// GetUpdater is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) GetUpdater() UserPasshashUpdater {
	return NewUserPasshashUpdater(qs.db)
}

// IDEq is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) IDEq(ID int64) UserPasshashQuerySet {
	return qs.w(qs.db.Where("id = ?", ID))
}

// IDGt is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) IDGt(ID int64) UserPasshashQuerySet {
	return qs.w(qs.db.Where("id > ?", ID))
}

// IDGte is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) IDGte(ID int64) UserPasshashQuerySet {
	return qs.w(qs.db.Where("id >= ?", ID))
}

// IDIn is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) IDIn(ID ...int64) UserPasshashQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in IDIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("id IN (?)", ID))
}

// IDLt is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) IDLt(ID int64) UserPasshashQuerySet {
	return qs.w(qs.db.Where("id < ?", ID))
}

// IDLte is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) IDLte(ID int64) UserPasshashQuerySet {
	return qs.w(qs.db.Where("id <= ?", ID))
}

// IDNe is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) IDNe(ID int64) UserPasshashQuerySet {
	return qs.w(qs.db.Where("id != ?", ID))
}

// IDNotIn is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) IDNotIn(ID ...int64) UserPasshashQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in IDNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("id NOT IN (?)", ID))
}

// Limit is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) Limit(limit int) UserPasshashQuerySet {
	return qs.w(qs.db.Limit(limit))
}

// Offset is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) Offset(offset int) UserPasshashQuerySet {
	return qs.w(qs.db.Offset(offset))
}

// One is used to retrieve one result. It returns gorm.ErrRecordNotFound
// if nothing was fetched
func (qs UserPasshashQuerySet) One(ret *UserPasshash) error {
	return qs.db.First(ret).Error
}

// OrderAscByCreated is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) OrderAscByCreated() UserPasshashQuerySet {
	return qs.w(qs.db.Order("created ASC"))
}

// OrderAscByDeprecated is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) OrderAscByDeprecated() UserPasshashQuerySet {
	return qs.w(qs.db.Order("deprecated ASC"))
}

// OrderAscByID is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) OrderAscByID() UserPasshashQuerySet {
	return qs.w(qs.db.Order("id ASC"))
}

// OrderAscByPasshash is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) OrderAscByPasshash() UserPasshashQuerySet {
	return qs.w(qs.db.Order("passhash ASC"))
}

// OrderAscByUserID is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) OrderAscByUserID() UserPasshashQuerySet {
	return qs.w(qs.db.Order("user_id ASC"))
}

// OrderAscByVer is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) OrderAscByVer() UserPasshashQuerySet {
	return qs.w(qs.db.Order("ver ASC"))
}

// OrderDescByCreated is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) OrderDescByCreated() UserPasshashQuerySet {
	return qs.w(qs.db.Order("created DESC"))
}

// OrderDescByDeprecated is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) OrderDescByDeprecated() UserPasshashQuerySet {
	return qs.w(qs.db.Order("deprecated DESC"))
}

// OrderDescByID is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) OrderDescByID() UserPasshashQuerySet {
	return qs.w(qs.db.Order("id DESC"))
}

// OrderDescByPasshash is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) OrderDescByPasshash() UserPasshashQuerySet {
	return qs.w(qs.db.Order("passhash DESC"))
}

// OrderDescByUserID is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) OrderDescByUserID() UserPasshashQuerySet {
	return qs.w(qs.db.Order("user_id DESC"))
}

// OrderDescByVer is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) OrderDescByVer() UserPasshashQuerySet {
	return qs.w(qs.db.Order("ver DESC"))
}

// PasshashEq is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) PasshashEq(passhash string) UserPasshashQuerySet {
	return qs.w(qs.db.Where("passhash = ?", passhash))
}

// PasshashGt is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) PasshashGt(passhash string) UserPasshashQuerySet {
	return qs.w(qs.db.Where("passhash > ?", passhash))
}

// PasshashGte is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) PasshashGte(passhash string) UserPasshashQuerySet {
	return qs.w(qs.db.Where("passhash >= ?", passhash))
}

// PasshashIn is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) PasshashIn(passhash ...string) UserPasshashQuerySet {
	if len(passhash) == 0 {
		qs.db.AddError(errors.New("must at least pass one passhash in PasshashIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("passhash IN (?)", passhash))
}

// PasshashLike is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) PasshashLike(passhash string) UserPasshashQuerySet {
	return qs.w(qs.db.Where("passhash LIKE ?", passhash))
}

// PasshashLt is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) PasshashLt(passhash string) UserPasshashQuerySet {
	return qs.w(qs.db.Where("passhash < ?", passhash))
}

// PasshashLte is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) PasshashLte(passhash string) UserPasshashQuerySet {
	return qs.w(qs.db.Where("passhash <= ?", passhash))
}

// PasshashNe is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) PasshashNe(passhash string) UserPasshashQuerySet {
	return qs.w(qs.db.Where("passhash != ?", passhash))
}

// PasshashNotIn is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) PasshashNotIn(passhash ...string) UserPasshashQuerySet {
	if len(passhash) == 0 {
		qs.db.AddError(errors.New("must at least pass one passhash in PasshashNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("passhash NOT IN (?)", passhash))
}

// PasshashNotlike is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) PasshashNotlike(passhash string) UserPasshashQuerySet {
	return qs.w(qs.db.Where("passhash NOT LIKE ?", passhash))
}

// PreloadUser is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) PreloadUser() UserPasshashQuerySet {
	return qs.w(qs.db.Preload("User"))
}

// UserIDEq is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) UserIDEq(userID int64) UserPasshashQuerySet {
	return qs.w(qs.db.Where("user_id = ?", userID))
}

// UserIDGt is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) UserIDGt(userID int64) UserPasshashQuerySet {
	return qs.w(qs.db.Where("user_id > ?", userID))
}

// UserIDGte is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) UserIDGte(userID int64) UserPasshashQuerySet {
	return qs.w(qs.db.Where("user_id >= ?", userID))
}

// UserIDIn is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) UserIDIn(userID ...int64) UserPasshashQuerySet {
	if len(userID) == 0 {
		qs.db.AddError(errors.New("must at least pass one userID in UserIDIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("user_id IN (?)", userID))
}

// UserIDLt is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) UserIDLt(userID int64) UserPasshashQuerySet {
	return qs.w(qs.db.Where("user_id < ?", userID))
}

// UserIDLte is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) UserIDLte(userID int64) UserPasshashQuerySet {
	return qs.w(qs.db.Where("user_id <= ?", userID))
}

// UserIDNe is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) UserIDNe(userID int64) UserPasshashQuerySet {
	return qs.w(qs.db.Where("user_id != ?", userID))
}

// UserIDNotIn is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) UserIDNotIn(userID ...int64) UserPasshashQuerySet {
	if len(userID) == 0 {
		qs.db.AddError(errors.New("must at least pass one userID in UserIDNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("user_id NOT IN (?)", userID))
}

// VerEq is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) VerEq(ver int) UserPasshashQuerySet {
	return qs.w(qs.db.Where("ver = ?", ver))
}

// VerGt is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) VerGt(ver int) UserPasshashQuerySet {
	return qs.w(qs.db.Where("ver > ?", ver))
}

// VerGte is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) VerGte(ver int) UserPasshashQuerySet {
	return qs.w(qs.db.Where("ver >= ?", ver))
}

// VerIn is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) VerIn(ver ...int) UserPasshashQuerySet {
	if len(ver) == 0 {
		qs.db.AddError(errors.New("must at least pass one ver in VerIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("ver IN (?)", ver))
}

// VerLt is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) VerLt(ver int) UserPasshashQuerySet {
	return qs.w(qs.db.Where("ver < ?", ver))
}

// VerLte is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) VerLte(ver int) UserPasshashQuerySet {
	return qs.w(qs.db.Where("ver <= ?", ver))
}

// VerNe is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) VerNe(ver int) UserPasshashQuerySet {
	return qs.w(qs.db.Where("ver != ?", ver))
}

// VerNotIn is an autogenerated method
// nolint: dupl
func (qs UserPasshashQuerySet) VerNotIn(ver ...int) UserPasshashQuerySet {
	if len(ver) == 0 {
		qs.db.AddError(errors.New("must at least pass one ver in VerNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("ver NOT IN (?)", ver))
}

// SetCreated is an autogenerated method
// nolint: dupl
func (u UserPasshashUpdater) SetCreated(created time.Time) UserPasshashUpdater {
	u.fields[string(UserPasshashDBSchema.Created)] = created
	return u
}

// SetDeprecated is an autogenerated method
// nolint: dupl
func (u UserPasshashUpdater) SetDeprecated(deprecated bool) UserPasshashUpdater {
	u.fields[string(UserPasshashDBSchema.Deprecated)] = deprecated
	return u
}

// SetID is an autogenerated method
// nolint: dupl
func (u UserPasshashUpdater) SetID(ID int64) UserPasshashUpdater {
	u.fields[string(UserPasshashDBSchema.ID)] = ID
	return u
}

// SetPasshash is an autogenerated method
// nolint: dupl
func (u UserPasshashUpdater) SetPasshash(passhash string) UserPasshashUpdater {
	u.fields[string(UserPasshashDBSchema.Passhash)] = passhash
	return u
}

// SetUser is an autogenerated method
// nolint: dupl
func (u UserPasshashUpdater) SetUser(user User) UserPasshashUpdater {
	u.fields[string(UserPasshashDBSchema.User)] = user
	return u
}

// SetUserID is an autogenerated method
// nolint: dupl
func (u UserPasshashUpdater) SetUserID(userID int64) UserPasshashUpdater {
	u.fields[string(UserPasshashDBSchema.UserID)] = userID
	return u
}

// SetVer is an autogenerated method
// nolint: dupl
func (u UserPasshashUpdater) SetVer(ver int) UserPasshashUpdater {
	u.fields[string(UserPasshashDBSchema.Ver)] = ver
	return u
}

// Update is an autogenerated method
// nolint: dupl
func (u UserPasshashUpdater) Update() error {
	return u.db.Updates(u.fields).Error
}

// UpdateNum is an autogenerated method
// nolint: dupl
func (u UserPasshashUpdater) UpdateNum() (int64, error) {
	db := u.db.Updates(u.fields)
	return db.RowsAffected, db.Error
}

// ===== END of query set UserPasshashQuerySet

// ===== BEGIN of UserPasshash modifiers

// UserPasshashDBSchemaField describes database schema field. It requires for method 'Update'
type UserPasshashDBSchemaField string

// String method returns string representation of field.
// nolint: dupl
func (f UserPasshashDBSchemaField) String() string {
	return string(f)
}

// UserPasshashDBSchema stores db field names of UserPasshash
var UserPasshashDBSchema = struct {
	ID         UserPasshashDBSchemaField
	UserID     UserPasshashDBSchemaField
	User       UserPasshashDBSchemaField
	Passhash   UserPasshashDBSchemaField
	Deprecated UserPasshashDBSchemaField
	Ver        UserPasshashDBSchemaField
	Created    UserPasshashDBSchemaField
}{

	ID:         UserPasshashDBSchemaField("id"),
	UserID:     UserPasshashDBSchemaField("user_id"),
	User:       UserPasshashDBSchemaField("user"),
	Passhash:   UserPasshashDBSchemaField("passhash"),
	Deprecated: UserPasshashDBSchemaField("deprecated"),
	Ver:        UserPasshashDBSchemaField("ver"),
	Created:    UserPasshashDBSchemaField("created"),
}

// Update updates UserPasshash fields by primary key
// nolint: dupl
func (o *UserPasshash) Update(db *gorm.DB, fields ...UserPasshashDBSchemaField) error {
	dbNameToFieldName := map[string]interface{}{
		"id":         o.ID,
		"user_id":    o.UserID,
		"user":       o.User,
		"passhash":   o.Passhash,
		"deprecated": o.Deprecated,
		"ver":        o.Ver,
		"created":    o.Created,
	}
	u := map[string]interface{}{}
	for _, f := range fields {
		fs := f.String()
		u[fs] = dbNameToFieldName[fs]
	}
	if err := db.Model(o).Updates(u).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return err
		}

		return fmt.Errorf("can't update UserPasshash %v fields %v: %s",
			o, fields, err)
	}

	return nil
}

// UserPasshashUpdater is an UserPasshash updates manager
type UserPasshashUpdater struct {
	fields map[string]interface{}
	db     *gorm.DB
}

// NewUserPasshashUpdater creates new UserPasshash updater
// nolint: dupl
func NewUserPasshashUpdater(db *gorm.DB) UserPasshashUpdater {
	return UserPasshashUpdater{
		fields: map[string]interface{}{},
		db:     db.Model(&UserPasshash{}),
	}
}

// ===== END of UserPasshash modifiers

// ===== BEGIN of query set UserQuerySet

// UserQuerySet is an queryset type for User
type UserQuerySet struct {
	db *gorm.DB
}

// NewUserQuerySet constructs new UserQuerySet
func NewUserQuerySet(db *gorm.DB) UserQuerySet {
	return UserQuerySet{
		db: db.Model(&User{}),
	}
}

func (qs UserQuerySet) w(db *gorm.DB) UserQuerySet {
	return NewUserQuerySet(db)
}

func (qs UserQuerySet) Select(fields ...UserDBSchemaField) UserQuerySet {
	names := []string{}
	for _, f := range fields {
		names = append(names, f.String())
	}

	return qs.w(qs.db.Select(strings.Join(names, ",")))
}

// Create is an autogenerated method
// nolint: dupl
func (o *User) Create(db *gorm.DB) error {
	return db.Create(o).Error
}

// Delete is an autogenerated method
// nolint: dupl
func (o *User) Delete(db *gorm.DB) error {
	return db.Delete(o).Error
}

// ActiveEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) ActiveEq(active bool) UserQuerySet {
	return qs.w(qs.db.Where("active = ?", active))
}

// ActiveIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) ActiveIn(active ...bool) UserQuerySet {
	if len(active) == 0 {
		qs.db.AddError(errors.New("must at least pass one active in ActiveIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("active IN (?)", active))
}

// ActiveNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) ActiveNe(active bool) UserQuerySet {
	return qs.w(qs.db.Where("active != ?", active))
}

// ActiveNotIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) ActiveNotIn(active ...bool) UserQuerySet {
	if len(active) == 0 {
		qs.db.AddError(errors.New("must at least pass one active in ActiveNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("active NOT IN (?)", active))
}

// AddressEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) AddressEq(address string) UserQuerySet {
	return qs.w(qs.db.Where("address = ?", address))
}

// AddressGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) AddressGt(address string) UserQuerySet {
	return qs.w(qs.db.Where("address > ?", address))
}

// AddressGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) AddressGte(address string) UserQuerySet {
	return qs.w(qs.db.Where("address >= ?", address))
}

// AddressIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) AddressIn(address ...string) UserQuerySet {
	if len(address) == 0 {
		qs.db.AddError(errors.New("must at least pass one address in AddressIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("address IN (?)", address))
}

// AddressLike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) AddressLike(address string) UserQuerySet {
	return qs.w(qs.db.Where("address LIKE ?", address))
}

// AddressLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) AddressLt(address string) UserQuerySet {
	return qs.w(qs.db.Where("address < ?", address))
}

// AddressLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) AddressLte(address string) UserQuerySet {
	return qs.w(qs.db.Where("address <= ?", address))
}

// AddressNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) AddressNe(address string) UserQuerySet {
	return qs.w(qs.db.Where("address != ?", address))
}

// AddressNotIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) AddressNotIn(address ...string) UserQuerySet {
	if len(address) == 0 {
		qs.db.AddError(errors.New("must at least pass one address in AddressNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("address NOT IN (?)", address))
}

// AddressNotlike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) AddressNotlike(address string) UserQuerySet {
	return qs.w(qs.db.Where("address NOT LIKE ?", address))
}

// All is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) All(ret *[]User) error {
	return qs.db.Find(ret).Error
}

// AvatarEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) AvatarEq(avatar string) UserQuerySet {
	return qs.w(qs.db.Where("avatar = ?", avatar))
}

// AvatarGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) AvatarGt(avatar string) UserQuerySet {
	return qs.w(qs.db.Where("avatar > ?", avatar))
}

// AvatarGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) AvatarGte(avatar string) UserQuerySet {
	return qs.w(qs.db.Where("avatar >= ?", avatar))
}

// AvatarIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) AvatarIn(avatar ...string) UserQuerySet {
	if len(avatar) == 0 {
		qs.db.AddError(errors.New("must at least pass one avatar in AvatarIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("avatar IN (?)", avatar))
}

// AvatarLike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) AvatarLike(avatar string) UserQuerySet {
	return qs.w(qs.db.Where("avatar LIKE ?", avatar))
}

// AvatarLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) AvatarLt(avatar string) UserQuerySet {
	return qs.w(qs.db.Where("avatar < ?", avatar))
}

// AvatarLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) AvatarLte(avatar string) UserQuerySet {
	return qs.w(qs.db.Where("avatar <= ?", avatar))
}

// AvatarNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) AvatarNe(avatar string) UserQuerySet {
	return qs.w(qs.db.Where("avatar != ?", avatar))
}

// AvatarNotIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) AvatarNotIn(avatar ...string) UserQuerySet {
	if len(avatar) == 0 {
		qs.db.AddError(errors.New("must at least pass one avatar in AvatarNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("avatar NOT IN (?)", avatar))
}

// AvatarNotlike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) AvatarNotlike(avatar string) UserQuerySet {
	return qs.w(qs.db.Where("avatar NOT LIKE ?", avatar))
}

// Count is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) Count() (int, error) {
	var count int
	err := qs.db.Count(&count).Error
	return count, err
}

// Delete is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) Delete() error {
	return qs.db.Delete(User{}).Error
}

// DeleteNum is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) DeleteNum() (int64, error) {
	db := qs.db.Delete(User{})
	return db.RowsAffected, db.Error
}

// DeleteNumUnscoped is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) DeleteNumUnscoped() (int64, error) {
	db := qs.db.Unscoped().Delete(User{})
	return db.RowsAffected, db.Error
}

// EmailEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailEq(email string) UserQuerySet {
	return qs.w(qs.db.Where("email = ?", email))
}

// EmailGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailGt(email string) UserQuerySet {
	return qs.w(qs.db.Where("email > ?", email))
}

// EmailGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailGte(email string) UserQuerySet {
	return qs.w(qs.db.Where("email >= ?", email))
}

// EmailIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailIn(email ...string) UserQuerySet {
	if len(email) == 0 {
		qs.db.AddError(errors.New("must at least pass one email in EmailIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("email IN (?)", email))
}

// EmailLike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailLike(email string) UserQuerySet {
	return qs.w(qs.db.Where("email LIKE ?", email))
}

// EmailLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailLt(email string) UserQuerySet {
	return qs.w(qs.db.Where("email < ?", email))
}

// EmailLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailLte(email string) UserQuerySet {
	return qs.w(qs.db.Where("email <= ?", email))
}

// EmailNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailNe(email string) UserQuerySet {
	return qs.w(qs.db.Where("email != ?", email))
}

// EmailNotIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailNotIn(email ...string) UserQuerySet {
	if len(email) == 0 {
		qs.db.AddError(errors.New("must at least pass one email in EmailNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("email NOT IN (?)", email))
}

// EmailNotlike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailNotlike(email string) UserQuerySet {
	return qs.w(qs.db.Where("email NOT LIKE ?", email))
}

// FullNameEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) FullNameEq(fullName string) UserQuerySet {
	return qs.w(qs.db.Where("full_name = ?", fullName))
}

// FullNameGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) FullNameGt(fullName string) UserQuerySet {
	return qs.w(qs.db.Where("full_name > ?", fullName))
}

// FullNameGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) FullNameGte(fullName string) UserQuerySet {
	return qs.w(qs.db.Where("full_name >= ?", fullName))
}

// FullNameIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) FullNameIn(fullName ...string) UserQuerySet {
	if len(fullName) == 0 {
		qs.db.AddError(errors.New("must at least pass one fullName in FullNameIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("full_name IN (?)", fullName))
}

// FullNameLike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) FullNameLike(fullName string) UserQuerySet {
	return qs.w(qs.db.Where("full_name LIKE ?", fullName))
}

// FullNameLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) FullNameLt(fullName string) UserQuerySet {
	return qs.w(qs.db.Where("full_name < ?", fullName))
}

// FullNameLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) FullNameLte(fullName string) UserQuerySet {
	return qs.w(qs.db.Where("full_name <= ?", fullName))
}

// FullNameNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) FullNameNe(fullName string) UserQuerySet {
	return qs.w(qs.db.Where("full_name != ?", fullName))
}

// FullNameNotIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) FullNameNotIn(fullName ...string) UserQuerySet {
	if len(fullName) == 0 {
		qs.db.AddError(errors.New("must at least pass one fullName in FullNameNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("full_name NOT IN (?)", fullName))
}

// FullNameNotlike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) FullNameNotlike(fullName string) UserQuerySet {
	return qs.w(qs.db.Where("full_name NOT LIKE ?", fullName))
}

// GetDB is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) GetDB() *gorm.DB {
	return qs.db
}

// GetUpdater is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) GetUpdater() UserUpdater {
	return NewUserUpdater(qs.db)
}

// IDEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDEq(ID int64) UserQuerySet {
	return qs.w(qs.db.Where("id = ?", ID))
}

// IDGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDGt(ID int64) UserQuerySet {
	return qs.w(qs.db.Where("id > ?", ID))
}

// IDGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDGte(ID int64) UserQuerySet {
	return qs.w(qs.db.Where("id >= ?", ID))
}

// IDIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDIn(ID ...int64) UserQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in IDIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("id IN (?)", ID))
}

// IDLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDLt(ID int64) UserQuerySet {
	return qs.w(qs.db.Where("id < ?", ID))
}

// IDLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDLte(ID int64) UserQuerySet {
	return qs.w(qs.db.Where("id <= ?", ID))
}

// IDNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDNe(ID int64) UserQuerySet {
	return qs.w(qs.db.Where("id != ?", ID))
}

// IDNotIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDNotIn(ID ...int64) UserQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in IDNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("id NOT IN (?)", ID))
}

// LastLoginEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) LastLoginEq(lastLogin time.Time) UserQuerySet {
	return qs.w(qs.db.Where("last_login = ?", lastLogin))
}

// LastLoginGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) LastLoginGt(lastLogin time.Time) UserQuerySet {
	return qs.w(qs.db.Where("last_login > ?", lastLogin))
}

// LastLoginGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) LastLoginGte(lastLogin time.Time) UserQuerySet {
	return qs.w(qs.db.Where("last_login >= ?", lastLogin))
}

// LastLoginIsNotNull is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) LastLoginIsNotNull() UserQuerySet {
	return qs.w(qs.db.Where("last_login IS NOT NULL"))
}

// LastLoginIsNull is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) LastLoginIsNull() UserQuerySet {
	return qs.w(qs.db.Where("last_login IS NULL"))
}

// LastLoginLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) LastLoginLt(lastLogin time.Time) UserQuerySet {
	return qs.w(qs.db.Where("last_login < ?", lastLogin))
}

// LastLoginLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) LastLoginLte(lastLogin time.Time) UserQuerySet {
	return qs.w(qs.db.Where("last_login <= ?", lastLogin))
}

// LastLoginNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) LastLoginNe(lastLogin time.Time) UserQuerySet {
	return qs.w(qs.db.Where("last_login != ?", lastLogin))
}

// Limit is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) Limit(limit int) UserQuerySet {
	return qs.w(qs.db.Limit(limit))
}

// Offset is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) Offset(offset int) UserQuerySet {
	return qs.w(qs.db.Offset(offset))
}

// One is used to retrieve one result. It returns gorm.ErrRecordNotFound
// if nothing was fetched
func (qs UserQuerySet) One(ret *User) error {
	return qs.db.First(ret).Error
}

// OrderAscByActive is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderAscByActive() UserQuerySet {
	return qs.w(qs.db.Order("active ASC"))
}

// OrderAscByAddress is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderAscByAddress() UserQuerySet {
	return qs.w(qs.db.Order("address ASC"))
}

// OrderAscByAvatar is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderAscByAvatar() UserQuerySet {
	return qs.w(qs.db.Order("avatar ASC"))
}

// OrderAscByEmail is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderAscByEmail() UserQuerySet {
	return qs.w(qs.db.Order("email ASC"))
}

// OrderAscByFullName is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderAscByFullName() UserQuerySet {
	return qs.w(qs.db.Order("full_name ASC"))
}

// OrderAscByID is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderAscByID() UserQuerySet {
	return qs.w(qs.db.Order("id ASC"))
}

// OrderAscByLastLogin is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderAscByLastLogin() UserQuerySet {
	return qs.w(qs.db.Order("last_login ASC"))
}

// OrderAscByPhoneNum is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderAscByPhoneNum() UserQuerySet {
	return qs.w(qs.db.Order("phone_num ASC"))
}

// OrderAscByRegisteredAt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderAscByRegisteredAt() UserQuerySet {
	return qs.w(qs.db.Order("registered_at ASC"))
}

// OrderAscByType is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderAscByType() UserQuerySet {
	return qs.w(qs.db.Order("type ASC"))
}

// OrderDescByActive is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderDescByActive() UserQuerySet {
	return qs.w(qs.db.Order("active DESC"))
}

// OrderDescByAddress is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderDescByAddress() UserQuerySet {
	return qs.w(qs.db.Order("address DESC"))
}

// OrderDescByAvatar is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderDescByAvatar() UserQuerySet {
	return qs.w(qs.db.Order("avatar DESC"))
}

// OrderDescByEmail is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderDescByEmail() UserQuerySet {
	return qs.w(qs.db.Order("email DESC"))
}

// OrderDescByFullName is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderDescByFullName() UserQuerySet {
	return qs.w(qs.db.Order("full_name DESC"))
}

// OrderDescByID is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderDescByID() UserQuerySet {
	return qs.w(qs.db.Order("id DESC"))
}

// OrderDescByLastLogin is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderDescByLastLogin() UserQuerySet {
	return qs.w(qs.db.Order("last_login DESC"))
}

// OrderDescByPhoneNum is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderDescByPhoneNum() UserQuerySet {
	return qs.w(qs.db.Order("phone_num DESC"))
}

// OrderDescByRegisteredAt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderDescByRegisteredAt() UserQuerySet {
	return qs.w(qs.db.Order("registered_at DESC"))
}

// OrderDescByType is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderDescByType() UserQuerySet {
	return qs.w(qs.db.Order("type DESC"))
}

// PhoneNumEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) PhoneNumEq(phoneNum string) UserQuerySet {
	return qs.w(qs.db.Where("phone_num = ?", phoneNum))
}

// PhoneNumGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) PhoneNumGt(phoneNum string) UserQuerySet {
	return qs.w(qs.db.Where("phone_num > ?", phoneNum))
}

// PhoneNumGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) PhoneNumGte(phoneNum string) UserQuerySet {
	return qs.w(qs.db.Where("phone_num >= ?", phoneNum))
}

// PhoneNumIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) PhoneNumIn(phoneNum ...string) UserQuerySet {
	if len(phoneNum) == 0 {
		qs.db.AddError(errors.New("must at least pass one phoneNum in PhoneNumIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("phone_num IN (?)", phoneNum))
}

// PhoneNumLike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) PhoneNumLike(phoneNum string) UserQuerySet {
	return qs.w(qs.db.Where("phone_num LIKE ?", phoneNum))
}

// PhoneNumLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) PhoneNumLt(phoneNum string) UserQuerySet {
	return qs.w(qs.db.Where("phone_num < ?", phoneNum))
}

// PhoneNumLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) PhoneNumLte(phoneNum string) UserQuerySet {
	return qs.w(qs.db.Where("phone_num <= ?", phoneNum))
}

// PhoneNumNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) PhoneNumNe(phoneNum string) UserQuerySet {
	return qs.w(qs.db.Where("phone_num != ?", phoneNum))
}

// PhoneNumNotIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) PhoneNumNotIn(phoneNum ...string) UserQuerySet {
	if len(phoneNum) == 0 {
		qs.db.AddError(errors.New("must at least pass one phoneNum in PhoneNumNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("phone_num NOT IN (?)", phoneNum))
}

// PhoneNumNotlike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) PhoneNumNotlike(phoneNum string) UserQuerySet {
	return qs.w(qs.db.Where("phone_num NOT LIKE ?", phoneNum))
}

// RegisteredAtEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) RegisteredAtEq(registeredAt time.Time) UserQuerySet {
	return qs.w(qs.db.Where("registered_at = ?", registeredAt))
}

// RegisteredAtGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) RegisteredAtGt(registeredAt time.Time) UserQuerySet {
	return qs.w(qs.db.Where("registered_at > ?", registeredAt))
}

// RegisteredAtGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) RegisteredAtGte(registeredAt time.Time) UserQuerySet {
	return qs.w(qs.db.Where("registered_at >= ?", registeredAt))
}

// RegisteredAtLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) RegisteredAtLt(registeredAt time.Time) UserQuerySet {
	return qs.w(qs.db.Where("registered_at < ?", registeredAt))
}

// RegisteredAtLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) RegisteredAtLte(registeredAt time.Time) UserQuerySet {
	return qs.w(qs.db.Where("registered_at <= ?", registeredAt))
}

// RegisteredAtNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) RegisteredAtNe(registeredAt time.Time) UserQuerySet {
	return qs.w(qs.db.Where("registered_at != ?", registeredAt))
}

// TypeEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) TypeEq(typeValue int) UserQuerySet {
	return qs.w(qs.db.Where("type = ?", typeValue))
}

// TypeGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) TypeGt(typeValue int) UserQuerySet {
	return qs.w(qs.db.Where("type > ?", typeValue))
}

// TypeGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) TypeGte(typeValue int) UserQuerySet {
	return qs.w(qs.db.Where("type >= ?", typeValue))
}

// TypeIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) TypeIn(typeValue ...int) UserQuerySet {
	if len(typeValue) == 0 {
		qs.db.AddError(errors.New("must at least pass one typeValue in TypeIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("type IN (?)", typeValue))
}

// TypeLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) TypeLt(typeValue int) UserQuerySet {
	return qs.w(qs.db.Where("type < ?", typeValue))
}

// TypeLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) TypeLte(typeValue int) UserQuerySet {
	return qs.w(qs.db.Where("type <= ?", typeValue))
}

// TypeNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) TypeNe(typeValue int) UserQuerySet {
	return qs.w(qs.db.Where("type != ?", typeValue))
}

// TypeNotIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) TypeNotIn(typeValue ...int) UserQuerySet {
	if len(typeValue) == 0 {
		qs.db.AddError(errors.New("must at least pass one typeValue in TypeNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("type NOT IN (?)", typeValue))
}

// SetActive is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetActive(active bool) UserUpdater {
	u.fields[string(UserDBSchema.Active)] = active
	return u
}

// SetAddress is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetAddress(address string) UserUpdater {
	u.fields[string(UserDBSchema.Address)] = address
	return u
}

// SetAvatar is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetAvatar(avatar string) UserUpdater {
	u.fields[string(UserDBSchema.Avatar)] = avatar
	return u
}

// SetEmail is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetEmail(email string) UserUpdater {
	u.fields[string(UserDBSchema.Email)] = email
	return u
}

// SetFullName is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetFullName(fullName string) UserUpdater {
	u.fields[string(UserDBSchema.FullName)] = fullName
	return u
}

// SetID is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetID(ID int64) UserUpdater {
	u.fields[string(UserDBSchema.ID)] = ID
	return u
}

// SetLastLogin is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetLastLogin(lastLogin *time.Time) UserUpdater {
	u.fields[string(UserDBSchema.LastLogin)] = lastLogin
	return u
}

// SetPhoneNum is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetPhoneNum(phoneNum string) UserUpdater {
	u.fields[string(UserDBSchema.PhoneNum)] = phoneNum
	return u
}

// SetRegisteredAt is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetRegisteredAt(registeredAt time.Time) UserUpdater {
	u.fields[string(UserDBSchema.RegisteredAt)] = registeredAt
	return u
}

// SetType is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetType(typeValue int) UserUpdater {
	u.fields[string(UserDBSchema.Type)] = typeValue
	return u
}

// Update is an autogenerated method
// nolint: dupl
func (u UserUpdater) Update() error {
	return u.db.Updates(u.fields).Error
}

// UpdateNum is an autogenerated method
// nolint: dupl
func (u UserUpdater) UpdateNum() (int64, error) {
	db := u.db.Updates(u.fields)
	return db.RowsAffected, db.Error
}

// ===== END of query set UserQuerySet

// ===== BEGIN of User modifiers

// UserDBSchemaField describes database schema field. It requires for method 'Update'
type UserDBSchemaField string

// String method returns string representation of field.
// nolint: dupl
func (f UserDBSchemaField) String() string {
	return string(f)
}

// UserDBSchema stores db field names of User
var UserDBSchema = struct {
	ID           UserDBSchemaField
	FullName     UserDBSchemaField
	Email        UserDBSchemaField
	PhoneNum     UserDBSchemaField
	Address      UserDBSchemaField
	Avatar       UserDBSchemaField
	Type         UserDBSchemaField
	Active       UserDBSchemaField
	LastLogin    UserDBSchemaField
	RegisteredAt UserDBSchemaField
}{

	ID:           UserDBSchemaField("id"),
	FullName:     UserDBSchemaField("full_name"),
	Email:        UserDBSchemaField("email"),
	PhoneNum:     UserDBSchemaField("phone_num"),
	Address:      UserDBSchemaField("address"),
	Avatar:       UserDBSchemaField("avatar"),
	Type:         UserDBSchemaField("type"),
	Active:       UserDBSchemaField("active"),
	LastLogin:    UserDBSchemaField("last_login"),
	RegisteredAt: UserDBSchemaField("registered_at"),
}

// Update updates User fields by primary key
// nolint: dupl
func (o *User) Update(db *gorm.DB, fields ...UserDBSchemaField) error {
	dbNameToFieldName := map[string]interface{}{
		"id":            o.ID,
		"full_name":     o.FullName,
		"email":         o.Email,
		"phone_num":     o.PhoneNum,
		"address":       o.Address,
		"avatar":        o.Avatar,
		"type":          o.Type,
		"active":        o.Active,
		"last_login":    o.LastLogin,
		"registered_at": o.RegisteredAt,
	}
	u := map[string]interface{}{}
	for _, f := range fields {
		fs := f.String()
		u[fs] = dbNameToFieldName[fs]
	}
	if err := db.Model(o).Updates(u).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return err
		}

		return fmt.Errorf("can't update User %v fields %v: %s",
			o, fields, err)
	}

	return nil
}

// UserUpdater is an User updates manager
type UserUpdater struct {
	fields map[string]interface{}
	db     *gorm.DB
}

// NewUserUpdater creates new User updater
// nolint: dupl
func NewUserUpdater(db *gorm.DB) UserUpdater {
	return UserUpdater{
		fields: map[string]interface{}{},
		db:     db.Model(&User{}),
	}
}

// ===== END of User modifiers

// ===== END of all query sets
